after-startup-command = [
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

on-focus-changed = [
  "exec-and-forget curl http://localhost:7776/aerospace/spaces/refresh",
]

exec-on-workspace-change = [
  '/bin/zsh',
  '-c',
  'curl "http://localhost:7776/aerospace/spaces/refresh?space=$AEROSPACE_FOCUSED_WORKSPACE"',
]

[key-mapping]
  preset = 'qwerty'

[gaps]
    inner.horizontal = 20
    inner.vertical =   20
    outer.left =       20
    outer.bottom =     20
    outer.top =        60
    outer.right =      20

[mode.main.binding]
    #alt-slash = 'layout tiles horizontal vertical'
    #alt-comma = 'layout accordion horizontal vertical'

    cmd-left = 'focus left'
    cmd-down = 'focus down'
    cmd-up = 'focus up'
    cmd-right = 'focus right'

    cmd-shift-left = 'move left'
    cmd-shift-down = 'move down'
    cmd-shift-up = 'move up'
    cmd-shift-right = 'move right'

    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'
    
    cmd-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
    cmd-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
    cmd-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
    cmd-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
    cmd-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
    cmd-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'
    cmd-shift-7 = 'move-node-to-workspace 7 --focus-follows-window'
    cmd-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
    cmd-shift-9 = 'move-node-to-workspace 9 --focus-follows-window'

    alt-f =  ['layout tiles floating']
    alt-q =  ['layout tiles accordion']
    alt-v =  ['join-with left']

[workspace-to-monitor-force-assignment]
    1 = '1'
    2 = '1'
    3 = '1'
    4 = '2'
    5 = '2'
    6 = '2'
    7 = '2'
    8 = 'built-in'
    9 = 'built-in'

[[on-window-detected]]
  if.app-id = 'com.microsoft.VSCode'
  run = ['move-node-to-workspace 1 --focus-follows-window']

[[on-window-detected]]
  if.app-id = 'net.kovidgoyal.kitty'
  run = ['move-node-to-workspace 3 --focus-follows-window']

[[on-window-detected]]
  if.app-id = 'com.brave.Browser'
  run = ['move-node-to-workspace 4 --focus-follows-window']
  
[[on-window-detected]]
  if.app-id = 'com.google.Chrome'
  run = ['move-node-to-workspace 4 --focus-follows-window']

[[on-window-detected]]
  if.app-id = 'com.microsoft.teams2'
  run = ['move-node-to-workspace 8 --focus-follows-window']

[[on-window-detected]]
  if.app-id = 'com.apple.Music'
  run = ['move-node-to-workspace 9 --focus-follows-window']
